# Generated by Django 2.2.7 on 2021-06-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=100)),
                ('Nick', models.CharField(max_length=20)),
                ('Correo_electronico', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=1024)),
            ],
        ),
    ]
